import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import materialGlyphMap from '@expo/vector-icons/build/vendor/react-native-vector-icons/glyphmaps/MaterialIcons.json';
import React from 'react';

const ICON_MAP = {
    add: 'add',
    'add-circle': 'add-circle-outline',
    'alert-circle': 'error-outline',
    airplane: 'air',
    analytics: 'analytics',
    'arrow-back': 'arrow-back',
    'arrow-forward': 'arrow-forward',
    calendar: 'calendar-month',
    'calendar-number-outline': 'event',
    'calendar-outline': 'calendar-month',
    'checkmark-circle': 'check-circle',
    checkmark: 'check',
    'chevron-back': 'arrow-back-ios-new',
    'chevron-forward': 'chevron-right',
    close: 'close',
    'close-circle': 'cancel',
    edit: 'edit',
    'ellipsis-horizontal': 'more-horiz',
    'ellipsis-vertical': 'more-vert',
    'email-check-outline': 'mail-outline',
    eye: 'visibility',
    'eye-off': 'visibility-off',
    'folder-open': 'folder-open',
    heart: 'favorite',
    'heart-half': 'favorite-border',
    'home-outline': 'home',
    'information-circle': 'info',
    'list-outline': 'format-list-bulleted',
    locate: 'my-location',
    location: 'place',
    'logo-apple': 'phone-iphone',
    'logo-google': 'g-translate',
    'mail-outline': 'mail-outline',
    medical: 'medical-services',
    medkit: 'medical-services',
    'medkit-outline': 'medical-services',
    notifications: 'notifications',
    'notifications-outline': 'notifications-none',
    people: 'groups',
    'people-outline': 'groups-2',
    person: 'person',
    'person-outline': 'person-outline',
    pulse: 'monitor-heart',
    remove: 'remove',
    'search-outline': 'search',
    'settings-outline': 'settings',
    'share-social-outline': 'share',
    sparkles: 'auto-awesome',
    speedometer: 'speed',
    star: 'star',
    'stats-chart': 'show-chart',
    sync: 'sync',
    thermometer: 'thermostat',
    'time-outline': 'schedule',
    'trending-down': 'trending-down',
    'trending-up': 'trending-up',
    walk: 'directions-walk',
    'walk-outline': 'directions-walk',
    warning: 'warning',
    'water-drop': 'water-drop',
    water: 'water-drop',
    'water-outline': 'water-drop',
    'medical-bag': 'medical-services',
    'briefcase-plus': 'medical-services',
};

export default function AppIcon({ name, ...rest }) {
    const mapped = ICON_MAP[name] ?? name;
    const resolvedName = materialGlyphMap[mapped] ? mapped : 'help-outline';
    return <MaterialIcons name={resolvedName} {...rest} />;
}
